evento-completo
joaovictorc92/calendario pull request #13
Opened 2020-01-30 03:20 UTC by joaovictorc92

Cadastro de evento completo e validação para verificar se há conflito de horários com outro evento já salvo.

2020-01-30 09:43 UTC, asouza requested changes

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/form/EventoForm.java
> +    @NotNull
Aqui você nem precisa do NotNull, já que já tem o NotEmpty e a variável está inicializada com o ArrayList.

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/form/NotificacaoForm.java
> +    private String tipoNotificacao;
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Aqui você pode receber a enum direto. Basta que o valor do parâmetro seja exatamente igual a enum e, no seu caso, já é :).

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/form/NotificacaoForm.java
> +    @NotEmpty(message = "Informe o tipo de notificação")
Recebendo como enum, você inclusive pode marcar aqui apenas como @NotNull.

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/form/NotificacaoForm.java
> +    private String unidadeTempo;
Mesma coisa do TipoNotificacao aqui :).

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/validacao/TipoNotificacaoValido.java
> +public class TipoNotificacaoValido implements Validator {
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Se receber como enum lá, esse validador já perde a necessidade de existir :)

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/validacao/UnidadeTempoValida.java
> +public class UnidadeTempoValida implements Validator {
Mesma coisa aqui, boas chances de poder ser apagada :)

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/controller/validacao/VerificaConflitoHorarioEvento.java
> +        if(eventos!=null && !eventos.isEmpty()){
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Não tem chance do retorno aqui ser nulo. O Spring Data JPA nunca te retorna nulo :). Ele segue a regra *Não retornamos nulo dentro das regras da aplicação. Pense que seu computador vai explodir.* :P

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/model/enums/TipoNotificacao.java
> +    public static boolean contains(String value){
Esse método provavelmente vai morrer também :)

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/model/enums/UnidadeTempo.java
> +    public static boolean contains(String value){
Provavelmente vai morrer também :).

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/repository/EventoRepository.java
> +    @Query(value = "select * from evento " +
Curioso você ter feito uma query nativa aqui. Algum motivo especial?

2020-01-30 09:43 UTC, asouza commented on src/main/java/br/com/deveficiente/calendario/service/NovoEventoService.java
> +        if(eventoForm.getNotificacoes() != null){
*Não retornamos nulo dentro das regras da aplicação. Pense que seu computador vai explodir.*

Por mais que o DTO seja uma classe de borda e seja manter um código mais flexível nele, retornar null aumenta muito a chance do código gerar erro, principalmente NPE. Neste caso em específico, o form pode retornar a lista, mesmo que seja vazia. Aí fica tudo bem...

2020-01-31 00:37 UTC, joaovictorc92 commented on src/main/java/br/com/deveficiente/calendario/repository/EventoRepository.java
> +    @Query(value = "select * from evento " +
Costume e performance mesmo :)

2020-01-31 01:10 UTC, merged